### ISSUE TITLE
Too much fuel is added to Thing

### ISSUE THREAD

**Issue by WolfgangPolska** [jptrrs/BurnItForFuel#5]
Every time my pawns refuel things they seem to ignore  fuel levels in Thing and carry enough fuel to fill it to 100%, losing spare fuel in the process. Not only when adding one log, every time, on every patched thing.
![BugReprot](https://user-images.githubusercontent.com/47390891/72206914-ad446900-3493-11ea-8362-21629360c0b8.png)

**Comment by jptrrs** [comment]
Hi Wolfgang!
Thanks for reporting. I'll try to figure it out as soon as I can.

**Comment by jptrrs** [comment]
I managed to figure this out! Just uploaded a corrected version: https://github.com/jptrrs/BurnItForFuel/releases/tag/v1.3
What was happening was somewhat interesting. To make the multi-fuel selection work, I re-used a dead function that was still in the game code. It didn't appear it was being used by anything in vanilla, but it turns out the method that quantifies how much fuel is needed had a provision for that particular dead function. And that code branch couldn't do the math properly! 
Anyway, it's corrected in version 1.3.
Thanks for reporting!

**Comment by WolfgangPolska** [comment]
Thanks! Now I can use your mod in peace C;
